import type { Metadata } from "next";
import { demoMember } from "@/lib/data";
import { formatDate, formatKes } from "@/lib/utils";

export const metadata: Metadata = { title: "Statements" };

export default function StatementsPage() {
  return (
    <div className="mx-auto max-w-4xl">
      <h1 className="font-display text-3xl text-navy">Statements</h1>
      <p className="mt-2 text-muted">Downloadable PDFs will be generated by the core system. This is a preview list.</p>
      <div className="mt-8 overflow-hidden rounded-3xl bg-white shadow-sm">
        <table className="w-full text-left text-sm">
          <thead className="bg-cream text-xs uppercase tracking-wide text-muted">
            <tr>
              <th className="px-5 py-3 font-medium">Date</th>
              <th className="px-5 py-3 font-medium">Description</th>
              <th className="px-5 py-3 font-medium">Amount</th>
            </tr>
          </thead>
          <tbody>
            {demoMember.transactions.map((tx) => (
              <tr key={`${tx.date}-${tx.label}`} className="border-t border-navy/8">
                <td className="px-5 py-4 text-muted">{formatDate(tx.date)}</td>
                <td className="px-5 py-4 text-navy">{tx.label}</td>
                <td className="px-5 py-4">{formatKes(tx.amount)}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
